# Site settings
title: gpss.py
description: >-
  A silly, dumb, no-good Python program to read and run GPSS programs
baseurl: "/gpss.py"
url: "https://martendo.github.io"
author: martendo
github_repo: "https://github.com/martendo/gpss.py"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
