# Site settings
title: gpss.py
description: >-
  A Python implementation of IBM's General Purpose Simulation System
baseurl: "/gpss.py"
url: "https://martendo.github.io"
author: martendo
github_repo: "https://github.com/martendo/gpss.py"

# Build settings
theme: null

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
